#!/bin/bash

mkdir -p ./bin
env CGO_ENABLED=1 GO111MODULE=on go build -buildmode=plugin ./... ; rm src.so
if [ "$?" -ne "0" ] ; then exit 1 ; fi
env CGO_ENABLED=1 GO111MODULE=on go build -buildmode=plugin -o ./bin/ping.so ./src/ping.go
if [ "$?" -ne "0" ] ; then exit 1 ; else echo "Compiled ./src/ping.go -> ./bin/ping.go. Move into a bots plugin dir to use." ; fi
